config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  # get 'users/:id', to: 'users#show', as: 'profile'
  get 'profile', to: 'users#show'
  get 'users/:id/edit', to: 'users#edit', as: 'update_user'
  patch 'users/:id', to: 'users#update', as: 'edit_user'
  put 'users/:id', to: 'users#update'

  resources :workflows, only: [:new, :create, :update, :edit,:index, :show, :uploads]
  resources :programs, only: [ :show], as: 'icons'

  get 'program', to: 'workflows#index_by_program', as: :program
  get 'user_workflows', to: 'workflows#index_by_user', as: :user_workflows
  get 'workflows', to: 'workflows#uploads', as: :uploads

  get 'unapproved', to: 'workflows#index_by_unapproved', as: :unapproved

  resources :favourites, only: [:create, :destroy]
  get 'users/:id/favourites', to: 'favourites#index', as: 'favourited' do
    resources :workflows
  end
 get 'users/:id/uploads', to: 'favourites#index_uploads', as: 'uploaded' do
    resources :workflows
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :user
  belongs_to :workflow

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :workflow

end

app/models/program.rb
class Program < ApplicationRecord
has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  has_many :favourites, dependent: :destroy
  has_many :workflows

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :user_name, :email, :password, presence: true
  validates :email, :user_name, confirmation: true, uniqueness: true
  # validates :user_name
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/workflow.rb
class Workflow < ApplicationRecord
  has_one_attached :SDimage
  has_one_attached :SDprofile
  has_rich_text :content
  has_many :favourites, dependent: :destroy
  belongs_to :user
  validates :title,  :program, :loom_url, :approved, presence: true
  validates_length_of :title, :maximum => 50

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :user_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :user_name, :photo])
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :find_favourite, only: %i[show]
  before_action :find_workflow, only: %i[new create]

  def index
    @favourites = Favourite.where(user: current_user).order("created_at DESC")
    @favourites =  @favourites.paginate(page: params[:page], per_page: 8)
  end

  def index_uploads
    @uploads = Workflow.where(user_id: current_user).order("created_at DESC")
    @uploads =  @uploads.paginate(page: params[:page], per_page: 8)
  end

  def show
    @favourite = Favourite.find(params[:id])
  end

  def new
    @favourite = Favourite.new
  end

  def create
    @favourite = Favourite.new(favourite_params)

    # @favourite.workflow = Workflow.find(params[:workflow_id])
    # @favourite.user = current_user

    if @favourite.save
      @favourite.save!
      sleep(1.0)
      redirect_to workflow_path(@workflow)
    else
      render :new
    end
  end


  def destroy
  @favourite = Favourite.find(params[:id])
  @favourite.delete
    redirect_back(fallback_location: root_path)
  end

  private

  def find_favourite
    @favourite = Favourite.find(params[:id])
  end

  def find_workflow
    @workflow = Workflow.find(params["favourite"][:workflow_id])
  end

  def favourite_params
    params.require(:favourite).permit(:workflow_id,:user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController


def exist
@program

if Program.exists?(name: params[:filter])
then cl_image_tag Program.find_by(name: params[:filter]).photo.key
else
end

end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @email = @user.email
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to edit_user_path, notice: 'Profile was successfully updated 💥'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile_photo)
  end

end

app/controllers/workflows_controller.rb
class WorkflowsController < ApplicationController
  before_action :find_workflow, only: [:show, :edit]

  def index
    @workflows = Workflow.all.where(:approved => true ).order("created_at DESC")
    @workflows = @workflows.paginate(page: params[:page], per_page: 9)
  end

  def index_by_program
    if params[:filter]
      @workflows = Workflow.where(:program => params[:filter], :approved => true )
      @workflows =  @workflows.paginate(page: params[:page], per_page: 9)
    else
      @workflows = Workflow.all
      @workflows =  @workflows.paginate(page: params[:page], per_page: 9)
    end
  end

  def index_by_user
    if params[:filter]
      @user = User.where(user_name: params[:filter])
      @workflows = Workflow.where(:user_id => @user, :approved => true )
      @workflows =  @workflows.paginate(page: params[:page], per_page: 9)
    else
      @workflows = Workflow.all
      @workflows =  @workflows.paginate(page: params[:page], per_page: 9)
    end
  end

  def index_by_unapproved
      @workflows = Workflow.where(:approved => true )
      @workflows =  @workflows.paginate(page: params[:page], per_page: 9)
   
  end


  def index_by_user_unapproved
      @user = User.where(user_name: params[:filter])
      @workflows = Workflow.where(:user_id => @user, :approved => true )
      @workflows =  @workflows.paginate(page: params[:page], per_page: 9)
    
  end


  def new
    @workflow = Workflow.new
  end

  def create
    @workflow = Workflow.new(workflow_params)
    @workflow.user = current_user
    if @workflow.update(workflow_params)
      redirect_to workflow_path(@workflow), notice: '🎉 Workflow was successfully added'
    else
      render :new
    end
  end

  def edit
    @workflow_id = Workflow.find(params[:id])
  end

  def update
    @user = current_user
    @workflow = Workflow.find(params[:id])
    if @workflow.update(workflow_params)
      redirect_to workflow_path(@workflow), notice: '🎉 Workflow was successfully edited'
    else
      render :edit
    end
  end

  def show
    @workflow = Workflow.find(params[:id])
    @favourite = Favourite.new
  end

  def uploads
    @workflows = Workflow.all
  end

  private

  def workflow_params
    params.require(:workflow).permit(:title, :description, :walkthrough, :content, :program, :loom_url, :approved, :SDprofile, :SDimage)
  end

  def update_attributes
    params.require(:workflow).permit(:title, :description, :walkthrough, :content, :program, :loom_url, :approved, :SDprofile, :SDimage)
  end

  def find_workflow
    @workflow = Workflow.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
  <% else %>
    <%= link_to blob.filename, rails_blob_path(blob) %>
  <% end %>
</figure>

app/views/favourites/index_uploads.erb
 <!-- Page Content -->
  <div class="pt-5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-xl-12 col-lg-12 col-md-12 col-12">
          <!-- Bg -->
          <div class=" pt-16 rounded-top-md " style="
                   background: url(https://res.cloudinary.com/dza6mn30y/image/upload/v1645886041/Pushflo/Images/profile-bg_g0x3lh.jpg) no-repeat;
                    background-size: cover;">
          </div>
          <div
            class="d-flex align-items-end justify-content-between bg-white px-4  pt-2 pb-4 rounded-bottom-md shadow-sm ">
            <div class="d-flex align-items-center">
              <div class="me-2 position-relative d-flex justify-content-end align-items-end mt-n5">
                <img src="https://res.cloudinary.com/dza6mn30y/image/upload/v1646777172/Pushflo/Avatars/<%=current_user.first_name%>.jpg" class="avatar-xl rounded-circle border border-4 border-white"
                  alt="">
              </div>
              <div class="lh-1">
                <h2 class="mb-0"><%=@current_user.first_name%> <%=@current_user.last_name%>

                </h2>
                <p class=" mb-0 d-block"><%=@current_user.user_name%> </p>
              </div>
            </div>
            <div class="pt-lg-2">
             <%= link_to favourited_path do%>
             <button class="btn btn-outline-secondary mr-lg-2 mt-2 mb-0 hvr-icon-forward">
             ✨My Favourites <span>&nbsp;<i class = ""></i></span> <i class = "fa fa-chevron-circle-right fa-lg hvr-icon"></i>
                </button>

            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <!-- Content -->
      <div class="container pt-2">

<div class = "row ">

<div class= "col-8 pl-6 pt-3 pb-2">
      <h1 class= "text-black display-5"> &nbsp; ⤴️ My Uploads</h1>
</div>
<div class = "col-4 text-right pr-2" style = "padding:none !important;">
             <%= link_to "⤴️ Upload Workflow", new_workflow_path, class:"btn btn-primary  card-hover hvr-float mr-lg-4  mt-3" %>
</div>
</div>
  <div class="pb-5 py-md-3 px-0">
    <div class="container">
      <div class="row">
       <div class="row justify-content-center">
                  <div class="col-6 pl-3 ml-0 pb-2">
                    <%= will_paginate @uploads, renderer: WillPaginate::ActionView::BootstrapLinkRenderer , class: "container pb-lg-20 mr-0" %>
                  </div>
                  <div class="col-6 pr-0 mr-0">

                  <h4 class= "float-right  mr-0">💡Sorted by : <b>Most Recent</b></h4>
                  </div>

             </div>

      <div class="col-lg-3 col-md-4 col-12 pl-0 pr-">
					<!-- Side navbar -->
					<nav class="navbar navbar-expand-md navbar-light shadow-sm mb-4 pb-lg-2 sidenav">
						<!-- Menu -->
						<a class="d-xl-none d-lg-none d-md-none text-inherit fw-bold" href="#">Menu</a>
						<!-- Button -->
						<button class="navbar-toggler d-md-none icon-shape icon-sm rounded bg-primary text-light" type="button"
							data-bs-toggle="collapse" data-bs-target="#sidenav" aria-controls="sidenav" aria-expanded="false"
							aria-label="Toggle navigation">
							<span class="fe fe-menu"></span>
						</button>
						<!-- Collapse navbar -->
						<div class="collapse navbar-collapse" id="sidenav">
							<div class="navbar-nav flex-column ">

								<span class="navbar-header">⚙️ Account Settings</span>
                				<!-- List -->
								<ul class="list-unstyled ms-n2 mb-0">
									<!-- Nav item -->
									<li class="nav-item">
										<a class="nav-link" href="/profile"><i class="fe fe-settings nav-icon"></i>Edit Profile</a>
									</li>
								
									<li class="nav-item">
										<a class="nav-link" href="notifications.html"><i class="fe fe-bell nav-icon"></i>Notifications</a>
									</li>
									
									
								</ul>
								<span class="navbar-header border-top pt-3">😍 Favourites</span>
                				<!-- List -->
								<ul class="list-unstyled ms-n2 mb-2">
									<!-- Nav item -->
									<li class="nav-item">
										<a class="nav-link" href="/users/<%=current_user.id%>/favourites"><i class="fe fe-settings nav-icon"></i>My Favourites</a>
									</li>
			
								</ul>
								<span class="navbar-header border-top pt-3 ">🧐 Following</span>
                				<!-- List -->
								<ul class="list-unstyled ms-n2 mb-2">
									<!-- Nav item -->
									<li class="nav-item">
										<a class="nav-link" href="profile-edit.html"><i class="fe fe-settings nav-icon"></i>My Programs</a>
									</li>
								<!-- Nav item -->
									<li class="nav-item">
										<a class="nav-link" href="profile-edit.html"><i class="fe fe-settings nav-icon"></i>My Creators</a>
									</li>
			
								</ul>
								<span class="navbar-header border-top pt-3">⤴️ My Uploads</span>
                				<!-- List -->
								<ul class="list-unstyled ms-n2 mb-2">
									<!-- Nav item -->
									<li class="nav-item active">
										<a class="nav-link" href="/users/<%=current_user.id%>/uploads"><i class="fe fe-settings nav-icon"></i>My Uploads - Live</a>
									</li>
								<!-- Nav item -->
									<li class="nav-item">
										<a class="nav-link" href="profile-edit.html"><i class="fe fe-settings nav-icon"></i>Pending Review</a>
									</li>
									<!-- Nav item -->
									<li class="nav-item">
										<a class="nav-link" href="profile-edit.html"><i class="fe fe-settings nav-icon"></i>Denied</a>
									</li>
									
			
								</ul>
								<span class="navbar-header border-top pt-3">👨‍💼 Admin</span>
                				<!-- List -->
								<ul class="list-unstyled ms-n2 mb-4">
									<!-- Nav item -->
									<li class="nav-item">
										<a class="nav-link" href="/unapproved"><i class="fe fe-settings nav-icon"></i>To Review</a>
									</li>
								
									
			
								</ul>
							</div>
						</div>
					</nav>
				</div>






        <div class="col-xl-9 col-lg-9 col-md-8 col-12  px-0">


          <!-- Tab content -->

              <div class="row">

               

                <% @uploads.each do |upload|%>

                <div class="col-lg-4 col-md-6 col-12 ">


                  <!-- Card -->
                  <div class="card  mb-4 card-hover ">
                    <iframe  class="card-img-top" src= <%= Workflow.find(upload.id).loom_url.gsub(/\bshare\b/, 'embed') %> webkitallowfullscreen mozallowfullscreen allowfullscreen alt=""
                        class="card-img-top rounded-top-md"></iframe>
                    <!-- Card body -->
                    <div class="card-body">
                         <h4 class="mb-1 text-truncate-line-2 text-inherit "> <%= link_to Workflow.find(upload.id).title, workflow_path(upload.id)%>
                         </h4>
                        <ul class="mb-0 list-inline">
                        <li class="list-inline-item"><i class="mdi mdi-clock-time-four-outline text-muted"></i><img src="https://res.cloudinary.com/dza6mn30y/image/upload/c_scale,w_15/v1647351098/Pushflo/Category%20Icons/<%= Workflow.find(upload.id).program%>.png" class="pb-1 img-fluid" alt="">&nbsp;<strong><%= link_to Workflow.find(upload.id).program, program_path(filter: Workflow.find(upload.id).program), class:"text-secondary"  %></strong>

                        </li>
                      </ul>


                    </div>
                    <!-- Card footer -->
                    <div class="card-footer">
                      <div class="row align-items-center g-0">
                        <div class="col-auto">
                          <img src="https://res.cloudinary.com/dza6mn30y/image/upload/v1646777172/Pushflo/Avatars/<%=current_user.first_name%>.jpg"  class="rounded-circle avatar-xs" alt="">
                        </div>
                        <div class="col ms-2">
                          <span><%= link_to User.find(Workflow.find(upload.id).user_id).first_name + " " + User.find(Workflow.find(upload.id).user_id).last_name, user_workflows_path(filter:User.find(Workflow.find(upload.id).user_id).user_name ) , class:"text-secondary" %></span>

                        </div>
                        <div class="col-auto">
                          <a href="#" class="removeBookmark">
                            <i class="mdi mdi-bookmark mdi-18px"></i>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <% end %>
                <div class="col-lg-3 col-md-6 col-12">

                <div class="col-lg-3 col-md-6 col-12">

                </div>
                <div class="col-lg-3 col-md-6 col-12">
              </div>
              </div>
            </div>



              </div>
              <div class="row">
                <div class="offset-lg-3 col-lg-6 col-md-12 col-12 text-center mt-5">

                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

<div class="container pt-16"> </div>

app/views/layouts/_content.html.erb
<div class="trix-content">
  <%= yield %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <%= favicon_link_tag %>
    <title>Pushflo  - Supercharge your Stream Deck Workflow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.3.1/css/hover.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>



  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <%# <script src="/app/javascript/packs/bootstrap.bundle.min.js"></script> %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%# <script src="/app/javascript/packs/theme.min.js" type="text/javascript"></script> %>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.5.1/dist/confetti.browser.min.js"></script>

  </body>
</html>

app/views/shared/_navbar.html.erb
<div class=" navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top ">
  <div class="container-fluid d-flex justify-content-between ">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dza6mn30y/image/upload/v1645875304/Pushflo/Branding/Icon_multicolour_g7gkay.png" %>
    <% end %>

  <div class="brand">
    <%# <a class="navbar-brand" href="#"> %>
      <img src="https://res.cloudinary.com/dza6mn30y/image/upload/v1645874190/Pushflo/Branding/the_Pushflo_Hub_Logo_xinztt.png" alt="Logo" style="width:300px;">
    <%# </a> %>
  </div>

        <div class="ms-auto mt-3 mt-lg-0">


  <button class="confetti-canon mr-lg-4 py-0 px-1 hvr-icon-spin" id="confetti-canon">
            <h1 class= "hvr-icon">🎉</h1>
                </button>


      <% if current_page?(workflows_path ) ||  current_page?(program_path)|| current_page?(user_workflows_path) || current_page?(root_path)|| current_page?(new_user_session_path)|| current_page?(user_session_path) || current_page?(users_sign_out_path) || current_page?(destroy_user_session_path) then %>

      <% else %>

   <%= link_to workflows_path  do %>
                <button class="btn btn-outline-primary mr-lg-5 hvr-icon-forward">
              All Workflows  <span>&nbsp;<i class = "fa fa-chevron-circle-right fa-lg hvr-icon"></i></span>
                </button>
              <% end %>
<% end %>
			</div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dza6mn30y/image/upload/v1646777172/Pushflo/Avatars/#{current_user.first_name}.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>


            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Account", profile_path, class: "dropdown-item" %>
              <%= link_to "My Favourites", favourited_path(current_user), class: "dropdown-item" %>
               <%= link_to "My Uploads", uploaded_path(current_user), class: "dropdown-item" %>
              <%# <%= link_to "My Uploads", "", class: "dropdown-item"  %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <!--li class="nav-item"-->
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="container mb-10"></div>

app/views/users/_form.html.erb
<%= simple_form_for(current_user) do |f| %>
>>>>>>> 41636a402427d980e83cd011ce2eb89d0c127712
  <!-- [...] -->
  <%= f.input :photo, as: :file %>
  <!-- [...] -->
<% end %>

app/views/users/edit.html.erb
<div class=>
  <%= simple_form_for @user, url: edit_user_path(@user) do |f| %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.label :profile_photo %>
    <%= f.file_field :profile_photo, label: 'Profile photo' %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/workflows/new.html.erb
  <div class="py-2 pt-lg-5 ">
    <div class="container">
      <div class="row">
        <div class="offset-lg-1 col-lg-10 col-md-12 col-12">
          <div class="d-lg-flex align-items-center justify-content-between">
            <!-- Content -->
            <div class="mb-4 mb-lg-0">
              <h2 class="display-4 fw-bold ">⤴️ Submit a New Workflow</h2>
              <p class="mb-0 text-black lead">

              </p>
            </div>
                <div>
                  <%# <%= link_to "Back to Profile", profile_path, class:"btn btn-primary  card-hover " %>
                  <%= link_to uploaded_path(current_user) do%>
                  <button class="btn btn-outline-dark profile-back mr-lg-2 mt-2 mb-0 hvr-icon-forward">
                  <img src="https://res.cloudinary.com/dza6mn30y/image/upload/v1646777172/Pushflo/Avatars/<%=current_user.first_name%>.jpg" id="img-uploaded" class="avatar-sm rounded-circle" alt="" />&nbsp; Back to My Uploads<span>&nbsp;<i class = ""></i></span> <i class = "fa fa-chevron-circle-right fa-lg hvr-icon"></i>
                  </button>

                  <% end %>
                   <%# <%= link_to "Favourites/Uploads", favourited_path(current_user), class:"btn btn-dark card-hover " %>
                </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container px-14 py-2 pb-4  ">
  <div id="loomrecord" class=""><button class="button-4 text center align-middle"><img src="https://res.cloudinary.com/dza6mn30y/image/upload/c_scale,h_28/v1646954811/Pushflo/Images/icons/Loom_bm_wr6oyl.png">  Record a Loom</button></div>
  </div>
  <!-- Page Content -->
  <div class="pb-10">
    <div class="container">
      <div id="courseForm" class="form-inputs text-dark-primary text-body-bold  px-12">
    <%= simple_form_for [@workflow] do |f| %>
    <%= f.error_notification %>

      <div class = "pb-2">
    <%= f.input :title, :required => false, :label => "✨ Title*" ,:label_html => { :class => 'form_label' }, :maxlength => 50 %>
      <%# <%= f.label :description, :required => false, :label => "❓Description" , as: :text, input_html: {rows: 1},:class => 'form_label'  <span class="form_h2"> - 1 sentence headline (OPTIONAL)</span> %>
     <%# <%= f.input :description, label: false , :input_html => {:rows => 1} %>

    <span id="body-count">0</span> <span> Characters - Max 50</span>
 </div>


    <div class = "py-2">
    <%= f.label :program, :required => false, :label => "🗃️ Program / Category*", :class => 'form_label'  %> <span class="form_h2"> - which program does it relate to?</span>

    <%= f.input :program,label: false , collection: [ "Outlook", "Notion", "Excel", "Loom", "Xero", "Dext", "Zoom", "Photoshop", "Premiere", "Ableton Live", "Gmail", "Snagit", "G Sheets", "VS Code", "Slack" ]%>
     </div>

    <%= f.label :content, :required => false, :label => "📝 Written Walkthough", :class => 'form_label'  %> <span class="form_h2"> (OPTIONAL)</span>
    <%= f.rich_text_area :content, :html => { :class => 'form_walkthrough' } %>
    <div class = "pb-3 pt-2">
    <%= f.label :loom_url, :required => false, :label => "🎥 Loom video*", :class => 'form_label' %> <span class="form_h2"> - URL link (OPTIONAL)</span>
    <%= f.input :loom_url, label: false   %>
    </div>
    <span> <img class= "pl-2 pb-2" src="https://res.cloudinary.com/dza6mn30y/image/upload/c_scale,h_30/v1647337283/Pushflo/Images/icons/SD_Icon_rounded_isvkcm.png"></span><span class="form_h2"> - <strong> 🔗 STREAM DECK Profile</strong> (OPTIONAL)</span>
    <%= f.input :SDprofile, as: :file,  label: false, input_html: { id: "SD-button"}, required: false %>

<div class= "d-flex">


 <div class= "pt-lg-4 align-self-center  mr-4">
    <%= f.input :SDimage,  input_html: { class: 'd-none', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: "📷 Profile Screenshot" %>
</div>

<div class= "pt-lg-2 ">
 <%= image_tag "", width: 200, class: "hidden", id: "photo-preview" %>
 </div>
</div>

<%= f.hidden_field :user_id, value: current_user.id %>

<% if current_user.admin? %>
<%= f.hidden_field :approved, :value => true %>
<%else%>%  
<%f.hidden_field :approved, :value => false %>
<% end %>

<%= f.hidden_field :user_id, value: current_user.id %>

<% if current_user.admin? %>
<%then %>
  

    <div>
    <%= f.submit "🚀 Submit Workflow", class: " btn btn-primary submitbutton  card-hover mt-5  hvr-float" %>
    </div>
  

  <% else %>
  <div>
    <%= f.submit "🚀 Submit Workflow", class: " btn btn-primary submitbutton  card-hover mt-5  hvr-float" %>
    </div>

<% end %>
<% end %>

</div>

<div class="container pt-20"> </div>